# Generated by Django 6.1.1 on 2026-09-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المتجر')),
                ('slug', models.SlugField(unique=True, verbose_name='رابط المتجر (Slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores_images/', verbose_name='شعار المتجر')),
                ('link', models.URLField(verbose_name='رابط الموقع الرسمي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض أو الخصم')),
                ('code', models.CharField(max_length=50, verbose_name='كود الخصم')),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسبة أو قيمة الخصم')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل الشروط أو الوصف')),
                ('affiliate_link', models.URLField(verbose_name='رابط الأفلييت المخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل الكوبون فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='kob3.store', verbose_name='المتجر التابع له')),
            ],
        ),
    ]
