# Generated by Django 6.1.1 on 2026-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الشروط أو الوصف'),
        ),
    ]
