# Generated by Django 6.1.1 on 2026-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0002_alter_coupon_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('slug', models.SlugField(unique=True, verbose_name='رابط القسم(slug)')),
            ],
        ),
    ]
