# Generated by Django 6.1.1 on 2026-09-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='namee',
            new_name='name',
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='kob3.category', verbose_name='القسم'),
        ),
    ]
