# Generated by Django 6.1.1 on 2026-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0004_rename_namee_category_name_coupon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='offer_type',
            field=models.CharField(choices=[('coupon', 'كود خصك'), ('link', 'رابط عرض مباشر')], default='coupon', max_length=100, verbose_name='نوع العرض'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الأفلييت المخصص'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الخصم'),
        ),
    ]
