# Generated by Django 6.1.1 on 2026-09-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0005_coupon_offer_type_alter_coupon_affiliate_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Cat',
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='Sto',
        ),
        migrations.CreateModel(
            name='Cou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('coupon', 'كوبون خصم'), ('link', 'رابط عرض مباشر')], default='coupon', max_length=100, verbose_name='نوع العرض')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض أو الخصم')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الخصم')),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسبة أو قيمة الخصم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='تفاصيل الشروط أو الوصف')),
                ('affiliate_link', models.URLField(blank=True, null=True, verbose_name='رابط الأفلييت المخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل الكوبون فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='kob3.cat', verbose_name='القسم')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='kob3.sto', verbose_name='المتجر التابع له')),
            ],
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
