# Generated by Django 6.1.1 on 2026-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0006_rename_category_cat_rename_store_sto_cou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cou',
            name='offer_type',
            field=models.CharField(choices=[('couponn', 'كوبون خصم'), ('link', 'رابط عرض مباشر')], default='coupon', max_length=100, verbose_name='نوع العرض'),
        ),
    ]
