# Generated by Django 6.1.1 on 2026-09-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0007_alter_cou_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_images/', verbose_name='شعار القسم'),
        ),
        migrations.AlterField(
            model_name='cou',
            name='offer_type',
            field=models.CharField(choices=[('coupon', 'كوبون خصم'), ('link', 'رابط عرض مباشر')], default='coupon', max_length=100, verbose_name='نوع العرض'),
        ),
    ]
