# Generated by Django 6.1.1 on 2026-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0008_cat_image_alter_cou_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cou',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
    ]
