# Generated by Django 6.1.1 on 2026-09-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0009_cou_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cou',
            name='code',
        ),
    ]
