# Generated by Django 6.1.1 on 2026-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0010_remove_cou_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cou',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الخصم'),
        ),
    ]
