# Generated by Django 6.1.1 on 2026-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kob3', '0011_cou_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(choices=[('electronics', 'إلكترونيات وأجهزة ذكية'), ('fashion', 'أزياء وموضة'), ('perfumes', 'عطور ومساحيق تجميل'), ('food', 'طعام وتوصيل وجبات'), ('travel', 'سفر وتجارة دولية'), ('home', 'العناية بالمنزل والمنتجات اليومية'), ('health', 'الصحة والرياضة')], max_length=100, verbose_name='اسم القسم'),
        ),
    ]
